---
title: '0227'
author: "許晴雅"
date: "2020/3/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## package

```{r}
library(googlesheets4)
```
```{r}
a <- 2
a = 2 # = 與 <-同義
```

```{r}
3 -> b
```

## create objects

```{r}
my_108_total_credits <- 15
my.108.total_credits <- 15
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```
```{r}
`我的年紀` <- 20
my_age <- `我的年紀`
```
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```


```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```
```{r}
```


```{r}
library(googlesheets4)
`出席狀況表單網址` <-  "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表D` <- list(
  `108學年第1學期`=list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  `108學年第2學期`=list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```

```{r}
commit<-list(
  author=list(name="Martin老師",email="mtlin@gm.ntpu.edu.tw",time=ymd_hms("2020-03-25T07:17:40Z")),
  committer=list(name="emilyluckey",email="emily007@gmail.com",time=ymd_hms("2020-03-26T08:18:40Z")),
  message=list("update")
  )
print(commit)
```

```{r}
`小明`<-list(
  `108第一學期`=list(teacher1="Alice老師",course1="個體經濟學",score1="85分",
                 teacher2="Mark老師",course2="總體經濟學",score2="73分"),
  `108第二學期`=list(teacher1="Jason老師",course1="作業研究",score1="90分")
)
print(小明)
```

```{r}
`天氣預報`<-list(
  `台北市`=list(date1="2020-03-31",max1=25,min1=18,date2="2020-04-01",max2=25,min2=18),
`新北市`=list(
  date1="2020-03-31",max1=24,min1=15,date2="2020-04-01",max2=24,min2=15)
)
print(天氣預報)
```

```{r}
save(commit,`天氣預報`,`小明`,`小明108學年課表D`,file = "today.Rda")
```

```{r}
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters= list(`108-1`= list(year=108,semester=1,courses=list(
                list(name="個體經濟學",teacher="Alice",grade=85),
                list(name="總體經濟學",teacher="Mark",grade=78))),
        `108-2`=list(year=108,semester=2,courses=list(
                list(name="作業研究",teacher="Jason",grade=90
                )
              )
            )
      ) 
    )

```

```{r}
library(lubridate)
```

```{r}
time1<-ymd_hms("2020-03-04T06:45:00Z")
time2<-ymd_hms("2020-03-11 14:10:44",tz="Asia/Taipei")
time3<-ymd_hms("2020-03-11 14:28:28",tz="Asia/Taipei")
studientTime<-c(time1,time2,time3)
studientTime
class(time1)
typeof(time1)
as.numeric(time1)
```

```{r}
studentId <- c(410773002, 410773015)
class(studentId)
as.character(studentId)
```

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```

```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap

length(tainanSportsMap)
```

```{r}
tainanSportsMap[[1]]
```

```{r}
# 有多少名字可選：
names(listExample)
```

```{r}
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine

str(newTaipeiCityVaccine)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)
```

```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(1,2)]
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")]
listExample[c("student","學期")]
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```

```{r}
str(listExample[c(F,T)],max.level = 1) # 不要，要
str(listExample[c(T,T)],max.level = 1) # 要，要
```

```{r}
str(listExample[c(F,T)]) # 不要，要
str(listExample[c(T,T)]) # 要，要
```

```{r}
names(taipeiNightMarkets)
c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)->selectmarkets
str(taipeiNightMarkets[c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)],max.level = 1)
taipeiNightMarkets[selectmarkets]
```

```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
str(get1,max.level = 1)
str(get2,max.level = 2)
```

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```

```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)]
```

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
econOnly<-c(T,T,F,F,T)
names[econOnly]
gender[econOnly]
ecoFamilyOnly<-gender[econOnly][c(1,2)]
names[econOnly][c(1,2)]
```

```{r}
today <- list(
  list("台北市",highest_temp=c(highest_temp = 25),lowest_temp=c(lowest_temp = 18)),
  list("新北市",highest_temp=c(highest_temp = 24),lowest_temp=c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",highest_temp=c(highest_temp = 25),lowest_temp=c(lowest_temp = 18)),
  list("新北市",highest_temp=c(highest_temp = 24),lowest_temp=c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
```

```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a[[7]]<-"Johnson"
a<-c(a,"Mary")
a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}

list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
str(listExample)
```

```{r}
listExample[[2]][[1]][[2]]<-list(name="產業經濟學",teacher="Wen",grade="88")
str(listExample)
```

```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

```{r}
str(list1)
list1[[1]][-3] -> list1[[1]] # 小心回存的位置

list1[[2]][-c(4,5)] -> list1[[2]]
```

```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL
str(list1)
```

```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
#刪除新店區
newTaipeiYouBike[[1]][[5]]<-NULL
str(newTaipeiYouBike)
```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
a <- c(2, 3, 5)
b <- c(4,-1, 3)
a+b
a-b
a*b
a/b
a %% b
a ** b
```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
print(sequenceNums)

sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數
```

```{r}
5*c(1,3,4)+7
# 其實是
c(5)*c(1,3,4)+c(7)

## 對向量5，向量7進行recycle:
c(5,5,5)*c(1,3,4)+c(7,7,7)
## Recycle等長後才進行elementwise operation:
c(5*1+7, 5*3+7, 5*4+7)
```

```{r}
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)
# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)
```

```{r}
paste0(c("我叫"), c("小明","小美"))
paste0(c("我叫","我叫"), c("小明","小美"))
paste0(c("他叫","我叫"), c("小明","小美","大雄"))
```

